package utils

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

type NodeinfoSpec struct {
	Nodename   string `json:"nodename"`
	Macaddress string `json:"macaddress"`
}

type NodeinfoStatus struct {
}

type Nodeinfo struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NodeinfoSpec   `json:"spec,omitempty"`
	Status NodeinfoStatus `json:"status,omitempty"`
}

type NodeinfoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Nodeinfo `json:"items"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nodeinfo) DeepCopyInto(out *Nodeinfo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nodeinfo.
func (in *Nodeinfo) DeepCopy() *Nodeinfo {
	if in == nil {
		return nil
	}
	out := new(Nodeinfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Nodeinfo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeinfoList) DeepCopyInto(out *NodeinfoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Nodeinfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeinfoList.
func (in *NodeinfoList) DeepCopy() *NodeinfoList {
	if in == nil {
		return nil
	}
	out := new(NodeinfoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeinfoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeinfoSpec) DeepCopyInto(out *NodeinfoSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeinfoSpec.
func (in *NodeinfoSpec) DeepCopy() *NodeinfoSpec {
	if in == nil {
		return nil
	}
	out := new(NodeinfoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeinfoStatus) DeepCopyInto(out *NodeinfoStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeinfoStatus.
func (in *NodeinfoStatus) DeepCopy() *NodeinfoStatus {
	if in == nil {
		return nil
	}
	out := new(NodeinfoStatus)
	in.DeepCopyInto(out)
	return out
}
