apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snatpolicies.aci.snat
spec:
  group: aci.snat
  names:
    kind: SnatPolicy
    listKind: SnatPolicyList
    plural: snatpolicies
    singular: snatpolicy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            portRange:
              items:
                properties:
                  end:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                  start:
                    format: int64
                    maximum: 65535
                    minimum: 1
                    type: integer
                type: object
              type: array
            protocols:
              items:
                enum:
                - tcp
                - udp
                - icmp
                type: string
              type: array
            selector:
              properties:
                deployment:
                  type: string
                labels:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                namespace:
                  type: string
              type: object
            snatIp:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - snatIp
          - portRange
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
