apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snatglobalinfos.aci.snat
spec:
  group: aci.snat
  names:
    kind: SnatGlobalInfo
    listKind: SnatGlobalInfoList
    plural: snatglobalinfos
    singular: snatglobalinfo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            globalInfos:
              additionalProperties:
                items:
                  properties:
                    macAddress:
                      type: string
                    nodeName:
                      type: string
                    portRanges:
                      properties:
                        end:
                          format: int64
                          maximum: 65535
                          minimum: 1
                          type: integer
                        start:
                          format: int64
                          maximum: 65535
                          minimum: 1
                          type: integer
                      type: object
                    protocols:
                      items:
                        enum:
                        - tcp
                        - udp
                        - icmp
                        type: string
                      type: array
                    snatIpUid:
                      type: string
                  required:
                  - macAddress
                  - portRanges
                  - nodeName
                  - snatIpUid
                  - protocols
                  type: object
                type: array
              type: object
            snatType:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              enum:
              - selector
              - ' node'
              type: string
          required:
          - snatType
          - globalInfos
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
