apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: snat-operator
  namespace: foo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - nodes
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - snat-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - aci.snat
  - aci.nodeinfo
  resources:
  - '*'
  - snatips
  - snatallocations
  - nodeinfo
  verbs:
  - '*'
  - get
  - create
  - delete
  - update
